// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {monitoring} from '../models';
import {native} from '../models';
import {context} from '../models';

export function CreatePage(arg1:string,arg2:string,arg3:string):Promise<main.PageResult>;

export function DeletePage(arg1:string,arg2:string):Promise<main.PageResult>;

export function DeleteWidget(arg1:string,arg2:string,arg3:string):Promise<main.WidgetResult>;

export function GetGPUInfo():Promise<monitoring.GPUInfo>;

export function GetGPUProcesses():Promise<Array<monitoring.GPUProcess>>;

export function GetGPUProcessesDelta(arg1:string):Promise<monitoring.GPUProcessDeltaResponse>;

export function GetGPUProcessesFiltered(arg1:monitoring.GPUProcessQuery):Promise<monitoring.GPUProcessResponse>;

export function GetPages(arg1:string):Promise<main.PageResult>;

export function GetRealTimeMetrics():Promise<main.RealTimeMetrics>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetTopProcesses(arg1:number):Promise<Array<monitoring.ProcessInfo>>;

export function GetWidgets(arg1:string,arg2:string):Promise<main.WidgetResult>;

export function GetWindowState():Promise<native.WindowState>;

export function Greet(arg1:string):Promise<string>;

export function HideToTray():Promise<void>;

export function IsMonitoringRunning():Promise<boolean>;

export function KillGPUProcess(arg1:number):Promise<main.GPUProcessControlResult>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function ResumeGPUProcess(arg1:number):Promise<main.GPUProcessControlResult>;

export function SaveWidgets(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<main.WidgetResult>;

export function SetGPUProcessMonitoring(arg1:boolean):Promise<void>;

export function SetGPUProcessPriority(arg1:number,arg2:string):Promise<main.GPUProcessControlResult>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function SuspendGPUProcess(arg1:number):Promise<main.GPUProcessControlResult>;

export function UpdatePageName(arg1:string,arg2:string,arg3:string):Promise<main.PageResult>;

export function ValidateGPUProcess(arg1:number):Promise<main.GPUProcessValidationResult>;
