// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePage'](arg1, arg2, arg3);
}

export function DeletePage(arg1, arg2) {
  return window['go']['main']['App']['DeletePage'](arg1, arg2);
}

export function DeleteWidget(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteWidget'](arg1, arg2, arg3);
}

export function GetGPUInfo() {
  return window['go']['main']['App']['GetGPUInfo']();
}

export function GetGPUProcesses() {
  return window['go']['main']['App']['GetGPUProcesses']();
}

export function GetPages(arg1) {
  return window['go']['main']['App']['GetPages'](arg1);
}

export function GetRealTimeMetrics() {
  return window['go']['main']['App']['GetRealTimeMetrics']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTopProcesses(arg1) {
  return window['go']['main']['App']['GetTopProcesses'](arg1);
}

export function GetWidgets(arg1, arg2) {
  return window['go']['main']['App']['GetWidgets'](arg1, arg2);
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function IsMonitoringRunning() {
  return window['go']['main']['App']['IsMonitoringRunning']();
}

export function KillGPUProcess(arg1) {
  return window['go']['main']['App']['KillGPUProcess'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['main']['App']['OnStartup'](arg1);
}

export function ResumeGPUProcess(arg1) {
  return window['go']['main']['App']['ResumeGPUProcess'](arg1);
}

export function SaveWidgets(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWidgets'](arg1, arg2, arg3);
}

export function SetGPUProcessPriority(arg1, arg2) {
  return window['go']['main']['App']['SetGPUProcessPriority'](arg1, arg2);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function SuspendGPUProcess(arg1) {
  return window['go']['main']['App']['SuspendGPUProcess'](arg1);
}

export function UpdatePageName(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePageName'](arg1, arg2, arg3);
}

export function ValidateGPUProcess(arg1) {
  return window['go']['main']['App']['ValidateGPUProcess'](arg1);
}
