// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function CreatePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePage'](arg1, arg2, arg3);
}

export function DeleteAllWidgets(arg1, arg2) {
  return window['go']['main']['App']['DeleteAllWidgets'](arg1, arg2);
}

export function DeletePage(arg1, arg2) {
  return window['go']['main']['App']['DeletePage'](arg1, arg2);
}

export function DeleteWidget(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteWidget'](arg1, arg2, arg3);
}

export function ExecuteRawSQL(arg1) {
  return window['go']['main']['App']['ExecuteRawSQL'](arg1);
}

export function GetGPUInfo() {
  return window['go']['main']['App']['GetGPUInfo']();
}

export function GetGPUProcesses() {
  return window['go']['main']['App']['GetGPUProcesses']();
}

export function GetGPUProcessesFiltered(arg1) {
  return window['go']['main']['App']['GetGPUProcessesFiltered'](arg1);
}

export function GetPages(arg1) {
  return window['go']['main']['App']['GetPages'](arg1);
}

export function GetRealTimeMetrics() {
  return window['go']['main']['App']['GetRealTimeMetrics']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTopProcesses(arg1) {
  return window['go']['main']['App']['GetTopProcesses'](arg1);
}

export function GetWidgets(arg1, arg2) {
  return window['go']['main']['App']['GetWidgets'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsMonitoringRunning() {
  return window['go']['main']['App']['IsMonitoringRunning']();
}

export function KillGPUProcess(arg1) {
  return window['go']['main']['App']['KillGPUProcess'](arg1);
}

export function LoadPages(arg1) {
  return window['go']['main']['App']['LoadPages'](arg1);
}

export function LoadWidgets(arg1, arg2) {
  return window['go']['main']['App']['LoadWidgets'](arg1, arg2);
}

export function OnStartup(arg1) {
  return window['go']['main']['App']['OnStartup'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RestoreDatabase(arg1) {
  return window['go']['main']['App']['RestoreDatabase'](arg1);
}

export function ResumeGPUProcess(arg1) {
  return window['go']['main']['App']['ResumeGPUProcess'](arg1);
}

export function SavePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePage'](arg1, arg2, arg3);
}

export function SaveWidget(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWidget'](arg1, arg2, arg3, arg4);
}

export function SaveWidgets(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWidgets'](arg1, arg2, arg3);
}

export function SetGPUProcessMonitoring(arg1) {
  return window['go']['main']['App']['SetGPUProcessMonitoring'](arg1);
}

export function SetGPUProcessPriority(arg1, arg2) {
  return window['go']['main']['App']['SetGPUProcessPriority'](arg1, arg2);
}

export function ShowFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowFileDialog'](arg1, arg2, arg3);
}

export function ShowMessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2, arg3);
}

export function ShowSaveDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1, arg2, arg3);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function SuspendGPUProcess(arg1) {
  return window['go']['main']['App']['SuspendGPUProcess'](arg1);
}

export function UpdatePageName(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePageName'](arg1, arg2, arg3);
}

export function ValidateGPUProcess(arg1) {
  return window['go']['main']['App']['ValidateGPUProcess'](arg1);
}
